[package]
name = "chat"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
rocket-include-static-resources = "0.10.5"
tripcode = "0.2"

[profile.release]
opt-level = "s"
lto = true
strip = true
