[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install --assume-yes libssl-dev musl-tools"
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install --assume-yes libssl-dev musl-tools"
]